---
# This playbook will install the zabbix agent
- name: Install Policy Coreutils package
  yum: name=policycoreutils state=present

- name: Install Libselinux-python
  yum: name=libselinux-python state=present

- name: Install libsemanage-python
  yum: name=libsemanage-python state=present

- name: Install Zabbix Repository
  yum: name={{zbx_repo}} state=present

- name: install zabbix agent packages
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - zabbix-agent-{{ zbx_agent_Version }}

- name: Install Zabbix Agent Config File
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf owner=root group=root mode=0644 backup=yes
  notify:
    - restart zabbix-agent

- name: Ensure Zabbix Agent is running
  service: name=zabbix-agent state=started enabled=yes
  notify:
    - restart zabbix-agent

- include: iptables.yml
  when: ansible_distribution_major_version == "6"

- name: Open the Firewalld port 10050/tcp on Zabbix-server
  firewalld: port=10050/tcp permanent=true state=enabled
  when: ansible_distribution_major_version == '7'

- name: Open the Firewalld port 10050/udp on Zabbix-server
  firewalld: port=10050/udp permanent=true state=enabled
  when: ansible_distribution_major_version == '7'

- name: Reload firewalld config
  service: name=firewalld state=reloaded
  when: ansible_distribution_major_version == '7'

- name: Make sure Firewalld is started
  service: name=firewalld state=started
  when: ansible_distribution_major_version == '7'

- name: Configure SELinux Policy zabbix
  seboolean: name=zabbix_can_network state=yes persistent=yes

- name: Create a new host or update an existing host's info
  local_action:
    module: zabbix_host
    server_url: "{{ server_url }}"
    login_user: "{{ login_user }}"
    login_password: "{{ login_password }}"
    host_name: "{{ ansible_hostname }}"
    host_groups: "{{ host_groups }}"
    link_templates: "{{ link_templates }}"
    status: "{{ status }}"
    state: "{{ state }}"
    interfaces:
      - type: 1
        main: 1
        useip: 1
        ip: "{{ ansible_default_ipv4.address }}"
        dns: ""
        port: 10050
    proxy: ""
  when: zbx_create_host == 1
